# Generated by Django 4.1.7 on 2023-02-26 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Cars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="brand_cars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="brand_cars"
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        auto_now_add=True, verbose_name="data_time_brand_cars"
                    ),
                ),
            ],
            options={
                "ordering": ("data",),
            },
        ),
        migrations.CreateModel(
            name="year_cars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="cars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_cars",
                        to="Cars.brand_cars",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_cards",
                        to="Cars.model_cards",
                    ),
                ),
            ],
        ),
    ]
