# Generated by Django 4.1.7 on 2023-02-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cars", "0002_brand_cars_year_cars_cars"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cars",
            options={
                "ordering": ("data",),
                "verbose_name": "Car",
                "verbose_name_plural": "Cars",
            },
        ),
        migrations.AddField(
            model_name="cars",
            name="data",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="data_cars"
            ),
        ),
    ]
