# Generated by Django 4.1.7 on 2023-02-26 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Cars", "0004_cars_image_car"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cars",
            name="model",
        ),
        migrations.AddField(
            model_name="cars",
            name="Fuel",
            field=models.CharField(
                choices=[(" gasoline", " gasoline"), ("diesel", "diesel")],
                default=1,
                max_length=150,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cars",
            name="Gearbox",
            field=models.CharField(
                choices=[("automatic", "automatic"), ("mechanics", "mechanics")],
                default=1,
                max_length=150,
                verbose_name="Gearbox_cars",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cars",
            name="Passenger_Capacity",
            field=models.IntegerField(default=1, verbose_name="Passenger_Capacity"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cars",
            name="availability",
            field=models.BooleanField(default=False, verbose_name="availability_cars"),
        ),
        migrations.AddField(
            model_name="cars",
            name="guys",
            field=models.CharField(
                choices=[
                    ("SUV", "SUV"),
                    (" Pickup (Camioneta)", " Pickup (Camioneta)"),
                ],
                default=1,
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cars",
            name="price",
            field=models.ImageField(default=1, upload_to="", verbose_name="price_cars"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cars",
            name="year",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Cars.year_cars",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="model_cards",
        ),
    ]
