# Generated by Django 4.1.7 on 2023-02-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cars", "0009_alter_cars_maximum_baggage"),
    ]

    operations = [
        migrations.AddField(
            model_name="cars",
            name="model",
            field=models.CharField(
                default=1, max_length=150, unique=True, verbose_name="model car"
            ),
            preserve_default=False,
        ),
    ]
