# Generated by Django 4.1.7 on 2023-02-27 00:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cars", "0012_alter_year_cars_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="year_cars",
            name="year",
            field=models.PositiveIntegerField(
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(2018),
                    django.core.validators.MaxLengthValidator(2023),
                ],
                verbose_name="year_cars",
            ),
        ),
    ]
