# Generated by Django 4.1.7 on 2023-03-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cars", "0015_alter_cars_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cars",
            name="description",
            field=models.TextField(default=1, verbose_name="description"),
            preserve_default=False,
        ),
    ]
