# Generated by Django 4.1.7 on 2023-03-23 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Cars", "0016_cars_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cars",
            name="description",
        ),
    ]
