# Generated by Django 4.1.7 on 2023-03-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cars", "0017_remove_cars_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="Fuel",
            field=models.CharField(
                choices=[
                    (" gasoline", " gasoline"),
                    ("diesel", "diesel"),
                    ("electric", "electric"),
                ],
                max_length=150,
            ),
        ),
    ]
