# Generated by Django 4.1.7 on 2023-03-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Cars", "0018_alter_cars_fuel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand_cars",
            options={"ordering": ["brand"]},
        ),
    ]
