# Generated by Django 4.1.7 on 2023-02-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cars", "0003_alter_cars_options_cars_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="cars",
            name="image_car",
            field=models.ImageField(default=1, upload_to="image/cars"),
            preserve_default=False,
        ),
    ]
