# Generated by Django 4.1.7 on 2023-02-26 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Cars", "0006_alter_cars_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="guys_cars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guys",
                    models.CharField(
                        blank=True, max_length=200, unique=True, verbose_name="guys car"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="cars",
            name="Gearbox",
            field=models.CharField(
                choices=[("automatic", "automatic"), ("mechanics", "mechanics")],
                max_length=150,
                verbose_name="Gearbox_car",
            ),
        ),
        migrations.AlterField(
            model_name="cars",
            name="availability",
            field=models.BooleanField(default=False, verbose_name="availability_car"),
        ),
        migrations.AlterField(
            model_name="cars",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brand_car",
                to="Cars.brand_cars",
            ),
        ),
        migrations.AlterField(
            model_name="cars",
            name="data",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="data_car"
            ),
        ),
        migrations.AlterField(
            model_name="cars",
            name="price",
            field=models.IntegerField(verbose_name="price_car"),
        ),
        migrations.AlterField(
            model_name="cars",
            name="guys",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="guys_cars",
                to="Cars.guys_cars",
            ),
        ),
    ]
