# Generated by Django 4.1.7 on 2023-02-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cars", "0008_alter_brand_cars_options_alter_guys_cars_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="Maximum_Baggage",
            field=models.IntegerField(verbose_name="Maximum Baggage"),
        ),
    ]
