# Generated by Django 4.1.7 on 2023-02-27 00:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cars", "0011_year_cars_year_alter_cars_maximum_baggage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="year_cars",
            name="year",
            field=models.PositiveIntegerField(
                unique=True,
                validators=[django.core.validators.MinValueValidator(2018)],
                verbose_name="year_cars",
            ),
        ),
    ]
