# Generated by Django 4.1.7 on 2023-02-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiles",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="users_img", verbose_name="image/users"
            ),
        ),
    ]
