# Generated by Django 4.1.7 on 2023-02-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profiles_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiles",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="image/users",
                verbose_name="user image",
            ),
        ),
    ]
