# Generated by Django 4.1.7 on 2023-03-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profiles_is_validate_profiles_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="profiles",
            name="opt",
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
