# Generated by Django 4.1.7 on 2023-03-10 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_profiles_opt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profiles",
            name="otp",
        ),
    ]
