# Generated by Django 4.1.7 on 2023-03-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_profiles_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="profiles",
            name="Country",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Country"
            ),
        ),
        migrations.AddField(
            model_name="profiles",
            name="Street",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Street"
            ),
        ),
        migrations.AddField(
            model_name="profiles",
            name="address",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="profiles",
            name="opt",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
