# Generated by Django 4.1.7 on 2023-03-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_profiles_country_profiles_street_profiles_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiles",
            name="Country",
            field=models.CharField(default=1, max_length=150, verbose_name="Country"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profiles",
            name="Street",
            field=models.CharField(default=1, max_length=50, verbose_name="Street"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profiles",
            name="address",
            field=models.CharField(default=1, max_length=250, verbose_name="Address"),
            preserve_default=False,
        ),
    ]
